### ISSUE TITLE
Gemnasium displaying invalid results

### ISSUE THREAD

**Issue by cvega** [MarkHerhold/IcedFrisby#17]
If you click the package dependencies badge on the readme it links to an invalid report.

Not sure what the mechanism is for gemnasium.com but it appears to be displaying results for packages that are no longer listed in package.json. If I can do anything to help please let me know.

**Comment by paulmelnikow** [comment]
The [Gemnasium link](https://gemnasium.com/RobertHerhold/IcedFrisby) is showing the former repo location (RobertHerhold/IcedFrisby). Maybe @MarkHerhold needs to re-configure it in the new location?

[Greenkeeper](https://greenkeeper.io/) has become popular. We could look at switching to that instead.

**Comment by MarkHerhold** [comment]
@RobertHerhold Can you fix/get rid of Germnasium please?
@paulmelnikow I can setup Greenkeeper if you like, but the downside is that it's pretty noisy. Let me know.

**Comment by paulmelnikow** [comment]
It did get a bit better in version 2. They make one thread per dependency now, instead of one per notification. I'm game to give it a shot.

**Comment by MarkHerhold** [comment]
@paulmelnikow I'm glad to hear they improved it. I just added it.

**Comment by RobertHerhold** [comment]
I removed this library from Gemnasium, but the link still works for some reason. Regardless, we should be fine to switch off of it.
