### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by paulmelnikow** [MarkHerhold/IcedFrisby#47]
I hardly want to bikeshed, though I wonder if we should drop semicolons. I've stopped using them in my own projects after being solidly in the Crockford camp for years. These two sources, along with the fabulous linters we have today, have convinced me:

- https://www.youtube.com/watch?v=Qlr-FGbhKaI
- http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding

IcedFrisby syntax in particular (and function chaining in general) looks nicer without semicolons, and is also much easier to modify. If I chain on more assertions, or remove some, I don't have to worry about placing the semicolon in the right place. If I add a callback with an arrow function I don't need to place the fussy semicolon inside it.

Where this would help most, internally, is the tests, where I've often run into this pain point.

Every line of `icedfrisby.js` is touched in #46, so git blame is useless right now. If we were to make the change, right now wouldn't be a bad time. When we do it on the other files, I'd want to fix the indentation at the same time.

Again, really don't want to bikeshed. This is about the least important thing I can think of.

**Comment by MarkHerhold** [comment]
I don't really care, but I tend to use them in my own code because there are very small readability edge cases. Here's an example:

```
// careful: will break
a = b + c
(d + e).print()
```
This is actually evaluated as:
```
a = b + c(d + e).print();
```

Source:
> http://mislav.net/2010/05/semicolons/

I don't like to take chances on stupid stuff like this for an extra character. I also don't hold git blame to very high regard (all your other refactoring work is killing it anyway) but you do whatever you are most comfortable with. Cheers!

**Comment by paulmelnikow** [comment]
Right, the edge cases are the thing. The most common is the one you show: a left bracket or a left paren at the beginning of a line. Unfortunately, since ASI can't be turned off, even if you insert all the (good) semicolons, you can't prevent JavaScript from inserting more (stupid) ones:

```js
function makeThing () {
  return
    {
      foo: 123
    };
}

console.log(makeThing());  // prints 'undefined'
```

Our lint rules (which pull in [no-unexpected-multiline](http://eslint.org/docs/rules/no-unexpected-multiline) and [no-unreachable](http://eslint.org/docs/rules/no-unreachable)) will catch both sets of problems, whether or not we have semis everywhere.

**Comment by MarkHerhold** [comment]
Ok, SGTM then
