### ISSUE TITLE
Clarify how joi should be installed

### ISSUE THREAD

**Issue by paulmelnikow** [MarkHerhold/IcedFrisby#52]
Joi is listed as a dependency of IcedFrisby. The install instructions suggest installing it separately, which makes sense since it needs to be required directly in the user's code.

It wouldn't be good to have multiple versions of Joi installed. So, the user could keep their joi version in sync with the version required by IcedFrisby. That could be fussy though.

Another option is to make it a peer dependency, meaning it has to be required separately, and npm will complain loudly when it is not installed. I've used this a lot with good success, and it tends to simplify upgrades quite a bit.

We could consider doing the same with chai.

Mocha is already a peer dependency.

**Comment by MarkHerhold** [comment]
We could also make Joi an export, but that ties the user to whatever version of Joi IcedFrisy uses.

**Comment by paulmelnikow** [comment]
Right. It would also require an application using Joi to make `icedfrisby` a `dependency` instead of a `devDependency`.

Another option is to make it an [`optionalDependency`](https://docs.npmjs.com/files/package.json#optionaldependencies). The Joi support in icedfrisby requires a Joi schema to be passed in, so the user will need to require Joi and create it themselves. This makes `optionalDependency` a nice option: the user needs to declare it as a dependency if and only if they are using – and requiring – it. The user also gets a lot of flexibility.

It seems like this is the situation `optionalDependency` is designed for!
