### ISSUE TITLE
Async support for before() and after()?

### ISSUE THREAD

**Issue by KiNgMaR** [MarkHerhold/IcedFrisby#57]
Hi there,

first off, many thanks for porting frisby to mocha. This is really a timesaver. 🥇 

Now it would be even more awesome if `before()`, `after()` and `finally()` also supported async functionality, e.g. like this:

    .before(function(done) {
        // ...
        server.listen(done);
    })
    .post(...)
    .expect(...)
    .finally(function(done) {
        // ...
        server.close(done);
    });

Would that be something you would accept as a PR? Thanks!

**Comment by paulmelnikow** [comment]
This sounds great to me!

I'd like to make this library work better with promises, including hooks which return promises. Though, that could easily be added later on.
