### ISSUE TITLE
Detach from upstream graph

### ISSUE THREAD

**Issue by paulmelnikow** [MarkHerhold/IcedFrisby#68]
I wanted to suggest we remove IcedFrisby repository from the Github repository graph. Which is to say, classify it as a standalone repository instead of a fork.

This is a good thing because Github treats forks differently: they don't come up in searches, they are not internally searchable, they have worse SEO. Initially we may take a small hit because I think our downstream forks will be disconnected, though overall I think this is worth it. It may help people find the project!

While this project is technically a fork of frisby, it's no longer really useful to think of it that way, at least in Github's sense of a fork.

@MarkHerhold if you agree, you'd need to contact Github by email to request this.

**Comment by MarkHerhold** [comment]
@paulmelnikow I completely agree. Submitting request.

**Comment by MarkHerhold** [comment]
Done!
