### ISSUE TITLE
setResponseX doesn't work

### ISSUE THREAD

**Issue by Fishbowler** [MarkHerhold/IcedFrisby#87]
This fails:

```
describe('Testing Overrides',function(){
    it('should expect modified requests to have been modified', function(){
        frisby.create('Add dummy header')
            .get('http://httpbin.org/get')
            .setResponseHeader('lol','rofl')
            .expectHeader('lol','rofl')
        .toss()
    })
})
```

The setResponseHeader and other setResponseX methods are Frisby legacy that existed to enable unit tests of the pathMatcher, but aren't used any more. Fix or remove?

**Comment by paulmelnikow** [comment]
Those methods are not in the API doc and the comment in our code says this:
```
/* Methods to manually set parts of the response for matcher testing */
```

Our comment suggests they are not useful for downstream testing. Thoughts or experience on whether or not that's true?

**Comment by Fishbowler** [comment]
As someone with an extensive suite of checks, I can't think of any good
reason to fake the result. You use IcedFrisby to test a thing, not to test
a faked version of the thing.

Happy to do the mini-PR for this.

**Comment by paulmelnikow** [comment]
Sounds good to me.

@MarkHerhold does that work for you?

**Comment by MarkHerhold** [comment]
Yes, SGTM

**Comment by paulmelnikow** [comment]
Cool.

We're about to do a major release on account of #84 so it's an especially good time to sneak this in!
